from pathlib import Path

BASE_DIRECTORY = Path(__file__).resolve().parent
CLIENT_DIRECTORY = (BASE_DIRECTORY / ".." / ".." / "client").resolve()
CLIENT_DIST_DIRECTORY = CLIENT_DIRECTORY / "dist"

ARTIFACTS_DIRECTORY = BASE_DIRECTORY / "artifacts"
VQNA_ARTIFACT_DIRECTORY = ARTIFACTS_DIRECTORY / "vqna"
CLIP_DOWNLOAD_DIRECTORY = ARTIFACTS_DIRECTORY / "clip"
VQNA_IMAGES_DIRECTORY = BASE_DIRECTORY / "images"

CLIP_MODEL_NAME = "ViT-L/14@336px"

MODEL_ENCODER_ANSWER_PATH = VQNA_ARTIFACT_DIRECTORY / "model_encoder_answer.pkl"
MODEL_ENCODER_ANSWER_TYPE_PATH = (
    VQNA_ARTIFACT_DIRECTORY / "model_encoder_answer_type.pkl"
)
MODEL_PATH = VQNA_ARTIFACT_DIRECTORY / "VisualQnA.pth"
